/**
 * Copyright [2013] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.jpa.modeler.specification.model;

import org.netbeans.jpa.modeler.spec.EntityMappings;
import org.netbeans.jpa.modeler.spec.design.Diagram;
import org.netbeans.jpa.modeler.spec.design.Plane;
import org.netbeans.modeler.config.element.ElementConfigFactory;
import org.netbeans.modeler.core.ModelerFile;
import org.netbeans.modeler.core.NBModelerUtil;

public class JPADefaultDiagramModel extends JPADiagramModel {

    @Override
    public void init(ModelerFile modelerFile) {
        ElementConfigFactory elementConfigFactory = modelerFile.getVendorSpecification().getElementConfigFactory();
        EntityMappings entityMappingsSpec = new EntityMappings();
        elementConfigFactory.initializeObjectValue(entityMappingsSpec);

//        entityMappingsSpec.setName(modelerFile.getName());
        entityMappingsSpec.setId(NBModelerUtil.getAutoGeneratedStringId());

        Diagram diagram = new Diagram();
        diagram.setId(NBModelerUtil.getAutoGeneratedStringId());
        Plane plane = new Plane();
        plane.setId(NBModelerUtil.getAutoGeneratedStringId() + "_p");
        diagram.setJPAPlane(plane);
        plane.setElementRef(entityMappingsSpec.getId());
        entityMappingsSpec.setJPADiagram(diagram);

        this.setDiagramElement(diagram);
        this.setDefinitionElement(entityMappingsSpec);
        this.setRootElement(entityMappingsSpec);

        this.getModelerScene().setRootElementSpec(entityMappingsSpec);
    }
}
