/**
 * Copyright [2014] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.jpa.modeler.generator.ui;

import java.io.File;

/**
 *
 * @author Gaurav Gupta
 */
public class ChooseLocationDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChooseLocationDialog
     */
    public ChooseLocationDialog(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null, null);
    }

    public ChooseLocationDialog(
            java.awt.Frame parent, boolean modal, File file, String title) {
        super(parent, modal);
        initComponents();

        setTitle(title);

        if (file != null && file.exists()) {
            locationChooser.setCurrentDirectory(file);
        }
    }

    public File getFolderLocation() {
        return locationChooser.getSelectedFile();
    }

    public void setFolderLocation(String val) {
        setFolderLocation(new File(val));
    }

    public void setFolderLocation(File val) {
        locationChooser.setSelectedFile(val);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Folder Location to Export Code");

        locationChooser.setAcceptAllFileFilterUsed(false);
        locationChooser.setApproveButtonMnemonic(2);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/netbeans/jpa/modeler/generator/ui/Bundle"); // NOI18N
        locationChooser.setApproveButtonText(bundle.getString("LBL_BrowseDialogApproveButton")); // NOI18N
        locationChooser.setApproveButtonToolTipText(bundle.getString("LBL_OpenButton_Tooltip")); // NOI18N
        locationChooser.setDialogTitle(bundle.getString("LBL_ChooseLocationDialog_Title")); // NOI18N
        locationChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        locationChooser.setBorder(null);
        locationChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(locationChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(locationChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationChooserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_locationChooserActionPerformed
    {//GEN-HEADEREND:event_locationChooserActionPerformed
        setVisible(false);
    }//GEN-LAST:event_locationChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseLocationDialog(
                        new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    public javax.swing.JFileChooser getLocationChooser() {
        return locationChooser;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser locationChooser;
    // End of variables declaration//GEN-END:variables

}
