//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.21 at 01:52:19 PM IST
//
package org.netbeans.jpa.modeler.spec;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for fetch-type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="fetch-type"> &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}token"> &lt;enumeration
 * value="LAZY"/> &lt;enumeration value="EAGER"/> &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "fetch-type")
@XmlEnum
public enum FetchType {

    LAZY("Lazy"),
    EAGER("Eager");

    private final String value;

    FetchType(String v) {
        value = v;
    }

    public String value() {
        return name();
    }

    public static FetchType fromValue(String v) {
        for (FetchType c : FetchType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
//    public String value() {
//        return name();
//    }

//    public static FetchType fromValue(String v) {
//        return valueOf(v);
//    }
}
