/**
 * Copyright [2014] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.jpa.modeler.navigator.classmember.panel;

import org.netbeans.jpa.modeler.navigator.tree.component.spec.CheckableAttributeNode;
import javax.swing.SwingUtilities;
import org.netbeans.jpa.modeler.core.widget.JavaClassWidget;
import org.netbeans.jpa.modeler.core.widget.PersistenceClassWidget;
import org.netbeans.jpa.modeler.navigator.classmember.component.CMRootNode;
import org.netbeans.jpa.modeler.navigator.entitygraph.component.EGInternalNode;
import org.netbeans.jpa.modeler.navigator.entitygraph.component.EGLeafNode;
import org.netbeans.jpa.modeler.navigator.entitygraph.component.EGRootNode;
import org.netbeans.jpa.modeler.navigator.tree.component.spec.TreeNode;
import org.netbeans.jpa.modeler.spec.ManagedClass;
import org.netbeans.jpa.modeler.spec.NamedAttributeNode;
import org.netbeans.jpa.modeler.spec.NamedEntityGraph;
import org.netbeans.jpa.modeler.spec.NamedSubgraph;
import org.netbeans.jpa.modeler.spec.extend.Attribute;
import org.netbeans.jpa.modeler.spec.extend.ClassMembers;
import org.netbeans.modeler.properties.embedded.GenericEmbeddedEditor;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.OutlineView;

public class ClassMemberPanel extends GenericEmbeddedEditor<ClassMembers> implements ExplorerManager.Provider {

    private final ExplorerManager manager;

    private ClassMembers classMembers;
    private final PersistenceClassWidget<? extends ManagedClass> persistenceClassWidget;
    private CMRootNode node;

    public ClassMemberPanel(PersistenceClassWidget<? extends ManagedClass> persistenceClassWidget) {
        this.persistenceClassWidget = persistenceClassWidget;
        manager = new ExplorerManager();
    }

    @Override
    public void init() {
        initComponents();
        SwingUtilities.invokeLater(() -> {
            node = new CMRootNode(persistenceClassWidget, classMembers, new ClassMemberChildFactory(), new CheckableAttributeNode(classMembers != null));
            manager.setRootContext(node);
        });
    }

    
       @Override
    public void setValue(ClassMembers classMembers) {
        this.classMembers=classMembers;
    }
    
        @Override
    public ClassMembers getValue() {
        return classMembers;
    }
//    @Override
//    public void createEntity(Class<? extends Entity> entityWrapperType) {
//        this.setTitle("Create new Named Entity Graph");
//        if (entityWrapperType == RowValue.class) {
//            this.setEntity(new RowValue(new Object[2]));
//        }
//        classMembers = null;
//    }

//    @Override
//    public void updateEntity(Entity<NamedEntityGraph> entityValue) {
//        this.setTitle("Update Named Entity Graph");
//        if (entityValue.getClass() == RowValue.class) {
//            this.setEntity(entityValue);
//            Object[] row = ((RowValue) entityValue).getRow();
//            classMembers = (NamedEntityGraph) row[0];
//        }
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootLayeredPane = new javax.swing.JLayeredPane();
        graphLayeredPane = new javax.swing.JLayeredPane();
        outlineView = new OutlineView("Entity Graph");

        graphLayeredPane.setLayout(new java.awt.GridLayout(1, 0));

        //outlineView.setDefaultActionAllowed(false);
        //outlineView.setDoubleBuffered(true);
        //outlineView.setDragSource(false);
        //outlineView.setDropTarget(false)
        graphLayeredPane.add(outlineView);

        javax.swing.GroupLayout rootLayeredPaneLayout = new javax.swing.GroupLayout(rootLayeredPane);
        rootLayeredPane.setLayout(rootLayeredPaneLayout);
        rootLayeredPaneLayout.setHorizontalGroup(
            rootLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        rootLayeredPaneLayout.setVerticalGroup(
            rootLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );
        rootLayeredPane.setLayer(graphLayeredPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootLayeredPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootLayeredPane)
        );
    }// </editor-fold>//GEN-END:initComponents

//    private boolean validateField() {
//        return true;
//    }

    void loadEntityGraph(NamedEntityGraph namedEntityGraph, TreeNode parentNode) {
        if (parentNode instanceof EGRootNode) {
            for (TreeNode childNode : ((EGRootNode) parentNode).getChildList()) {
                loadSubGraph(namedEntityGraph, childNode);
            }
        } else if (parentNode instanceof EGInternalNode) {
            for (TreeNode childNode : ((EGInternalNode) parentNode).getChildList()) {
                loadSubGraph(namedEntityGraph, childNode);
            }
        }

    }

    void loadSubGraph(NamedEntityGraph namedEntityGraph, TreeNode childNode) {
        if (childNode.getCheckableNode() != null && !childNode.getCheckableNode().isSelected()) {
            return;
        }

        if (childNode instanceof EGInternalNode) {
            String name = ((Attribute) (((EGInternalNode) childNode).getParentAttributeWidget().getBaseElementSpec())).getName();
            NamedAttributeNode attributeNode = new NamedAttributeNode(name);
            namedEntityGraph.addNamedAttributeNode(attributeNode);
            NamedSubgraph subGraph = new NamedSubgraph(name + ".Graph");
            for (TreeNode subChildNode : ((EGInternalNode) childNode).getChildList()) {
                loadSubGraph(namedEntityGraph, subGraph, subChildNode);
            }
            if (!subGraph.getNamedAttributeNode().isEmpty()) {
                namedEntityGraph.addSubgraph(subGraph);
                attributeNode.setSubgraph(subGraph.getName());
            }

        } else if (childNode instanceof EGLeafNode) {
            String name = ((Attribute) (((EGLeafNode) childNode).getLeafAttributeWidget().getBaseElementSpec())).getName();
            if (childNode.getCheckableNode().isCheckEnabled()) {
                namedEntityGraph.addNamedAttributeNode(new NamedAttributeNode(name));
            }
        }
    }

    void loadSubGraph(NamedEntityGraph namedEntityGraph, NamedSubgraph subGraph, TreeNode childNode) {
        if (childNode.getCheckableNode() != null && !childNode.getCheckableNode().isSelected()) {
            return;
        }
        if (childNode instanceof EGInternalNode) {
            String name = ((Attribute) (((EGInternalNode) childNode).getParentAttributeWidget().getBaseElementSpec())).getName();
            NamedAttributeNode attributeNode = new NamedAttributeNode(name);
            subGraph.addNamedAttributeNode(attributeNode);
            NamedSubgraph childSubGraph = new NamedSubgraph(name + ".Graph");
            for (TreeNode subChildNode : ((EGInternalNode) childNode).getChildList()) {
                loadSubGraph(namedEntityGraph, childSubGraph, subChildNode);
            }
            if (!childSubGraph.getNamedAttributeNode().isEmpty()) {
                namedEntityGraph.addSubgraph(childSubGraph);
                attributeNode.setSubgraph(childSubGraph.getName());
            }
        } else if (childNode instanceof EGLeafNode) {
            String name = ((Attribute) (((EGLeafNode) childNode).getLeafAttributeWidget().getBaseElementSpec())).getName();
            if (childNode.getCheckableNode().isCheckEnabled()) {
                subGraph.addNamedAttributeNode(new NamedAttributeNode(name));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane graphLayeredPane;
    private javax.swing.JScrollPane outlineView;
    private javax.swing.JLayeredPane rootLayeredPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return manager;
    }



}
