/**
 * This file was generated by the JPA Modeler
 */
package io.github.jeddict.jpa.employee;

import jakarta.persistence.Basic;
import jakarta.persistence.Entity;

@Entity
public class ContractEmployee extends Employee {

    @Basic
    private int dailyRate;

    @Basic
    private int term;

    public int getDailyRate() {
        return dailyRate;
    }

    public void setDailyRate(int dailyRate) {
        this.dailyRate = dailyRate;
    }

    public int getTerm() {
        return term;
    }

    public void setTerm(int term) {
        this.term = term;
    }

}