/**
 * This file was generated by the JPA Modeler
 */
package io.github.jeddict.jpa.employee;

import jakarta.persistence.Basic;
import jakarta.persistence.Entity;

@Entity
public class FullTimeEmployee extends CompanyEmployee {

    @Basic
    private long salary;

    @Basic
    private long pension;

    public long getSalary() {
        return salary;
    }

    public void setSalary(long salary) {
        this.salary = salary;
    }

    public long getPension() {
        return pension;
    }

    public void setPension(long pension) {
        this.pension = pension;
    }

}