/**
 * This file was generated by the JPA Modeler
 */
package io.github.jeddict.jpa.employee;

import jakarta.persistence.Basic;
import jakarta.persistence.Entity;

@Entity
public class PartTimeEmployee extends CompanyEmployee {

    @Basic
    private float hourlyRate;

    public float getHourlyRate() {
        return hourlyRate;
    }

    public void setHourlyRate(float hourlyRate) {
        this.hourlyRate = hourlyRate;
    }

}