/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.jpa.modeler.settings.code;

import java.util.prefs.Preferences;
import org.openide.util.NbPreferences;

public final class CodePanel extends javax.swing.JPanel {

    private final CodeOptionsPanelController controller;

    CodePanel(CodeOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refractorNamedQueryComp = new javax.swing.JCheckBox();
        deleteNamedQueryComp = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(refractorNamedQueryComp, org.openide.util.NbBundle.getMessage(CodePanel.class, "CodePanel.refractorNamedQueryComp.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(deleteNamedQueryComp, org.openide.util.NbBundle.getMessage(CodePanel.class, "CodePanel.deleteNamedQueryComp.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteNamedQueryComp)
                    .addComponent(refractorNamedQueryComp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refractorNamedQueryComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteNamedQueryComp)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
         refractorNamedQueryComp.setSelected(isRefractorQuery());
         deleteNamedQueryComp.setSelected(isDeleteQuery());
    }

    void store() {
       NbPreferences.forModule(CodePanel.class).putBoolean("refractorNamedQuery", refractorNamedQueryComp.isSelected());
       NbPreferences.forModule(CodePanel.class).putBoolean("deleteNamedQuery", deleteNamedQueryComp.isSelected());
       refractorNamedQuery=null;
       deleteNamedQuery=null;
    }

    private static Boolean deleteNamedQuery;
    private static Boolean refractorNamedQuery;
    public static boolean isRefractorQuery() {
        if (refractorNamedQuery == null) {
            refractorNamedQuery = pref.getBoolean("refractorNamedQuery", Boolean.TRUE);
        }
        return refractorNamedQuery;
    }
    
    public static boolean isDeleteQuery(){
        if (deleteNamedQuery == null) {
            deleteNamedQuery = pref.getBoolean("deleteNamedQuery", Boolean.FALSE);
        }
        return deleteNamedQuery;
    }
    
    boolean valid() {
        return true;
    }
    
private static final Preferences pref = NbPreferences.forModule(CodePanel.class);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox deleteNamedQueryComp;
    private javax.swing.JCheckBox refractorNamedQueryComp;
    // End of variables declaration//GEN-END:variables
}
