/**
 * Copyright [2016] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.db.modeler.properties.tablemember;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.netbeans.db.modeler.properties.tablemember.nodes.TableMemberChildFactory;
import org.netbeans.jpa.modeler.navigator.nodes.CheckableAttributeNode;
import javax.swing.SwingUtilities;
import org.netbeans.db.modeler.core.widget.table.TableWidget;
import org.netbeans.db.modeler.properties.order.OrderColumn;
import org.netbeans.db.modeler.properties.tablemember.nodes.TMLeafNode;
import org.netbeans.db.modeler.properties.tablemember.nodes.TMRootNode;
import org.netbeans.db.modeler.spec.DBTable;
import org.netbeans.jpa.modeler.navigator.nodes.TreeChildNode;
import org.netbeans.jpa.modeler.navigator.nodes.TreeNode;
import org.netbeans.jpa.modeler.navigator.nodes.TreeParentNode;
import org.netbeans.jpa.modeler.spec.OrderType;
import org.netbeans.jpa.modeler.spec.extend.OrderbyItem;
import org.netbeans.modeler.properties.embedded.GenericEmbeddedEditor;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.OutlineView;

public class TableMemberPanel extends GenericEmbeddedEditor<TableMembers> implements ExplorerManager.Provider {

    private TableMemberChildFactory childFactory;
    private ExplorerManager manager;
    private final String title;

    private TableMembers tableMembers;
    private TableWidget<? extends DBTable> tableWidget;
    private TMRootNode node;

    public TableMemberPanel(String title, TableWidget<? extends DBTable> tableWidget) {
        this.tableWidget = tableWidget;
        this.title = title;
    }

    public TableMemberPanel(String title) {
        this.title = title;
    }

    @Override
    public void init() {
        manager = new ExplorerManager();
        initComponents();
    }

    @Override
    public void setValue(TableMembers tableMembers) {
        this.tableMembers = tableMembers;
        SwingUtilities.invokeLater(() -> {
            if (childFactory == null) {
                node = new TMRootNode(getTableWidget(), tableMembers, new TableMemberChildFactory(), new CheckableAttributeNode());
            } else {
                node = new TMRootNode(getTableWidget(), tableMembers, childFactory, new CheckableAttributeNode());
            }
            manager.setRootContext(node);
            node.init();
        });
    }

    public void setValue(Set<OrderbyItem> columns) {
        TableMembers tableMembers_tmp = new TableMembers();
        tableMembers_tmp.setColumns(columns);
        setValue(tableMembers_tmp);
    }

    public void setValue(List<String> columns) {
        TableMembers tableMembers_tmp = new TableMembers();
        Set<OrderbyItem> columnData = new LinkedHashSet<>();
        columns.stream().forEach(c -> columnData.add(new OrderbyItem(c, OrderType.ASC)));
        tableMembers_tmp.setColumns(columnData);
        setValue(tableMembers_tmp);
    }

    @Override
    public TableMembers getValue() {
        tableMembers.getColumns().clear();
        loadTableMember(tableMembers, node);
        return tableMembers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootLayeredPane = new javax.swing.JLayeredPane();
        outlineView = new OutlineView(getTitle());

        rootLayeredPane.setLayout(new java.awt.GridLayout(1, 0));

        outlineView.setToolTipText(org.openide.util.NbBundle.getMessage(TableMemberPanel.class, "TableMemberPanel.outlineView.toolTipText")); // NOI18N
        rootLayeredPane.add(outlineView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadTableMember(TableMembers tableMembers, TreeNode parentNode) {
        if (parentNode instanceof TreeParentNode) {
            for (TreeNode childNode : ((TreeParentNode<TableMembers>) parentNode).getChildList()) {
                loadColumnNode(tableMembers, childNode);
            }
        }

    }

    private void loadColumnNode(TableMembers tableMembers, TreeNode childNode) {
        if (childNode.getCheckableNode() != null && !childNode.getCheckableNode().isSelected()) {
            return;
        }
        if (childNode instanceof TreeChildNode) {
            String column = (String) (((TMLeafNode) childNode).getLeafColumnWidget().getBaseElementSpec()).getName();
            if (childNode.getCheckableNode().isCheckEnabled()) {
                if (childNode instanceof OrderColumn) {
                    tableMembers.addColumn(column, ((OrderColumn) childNode).getOrder());
                } else {
                    tableMembers.addColumn(column);
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane outlineView;
    private javax.swing.JLayeredPane rootLayeredPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return manager;
    }

    /**
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * @return the tableWidget
     */
    public TableWidget<? extends DBTable> getTableWidget() {
        return tableWidget;
    }

    /**
     * @param tableWidget the tableWidget to set
     */
    public void setTableWidget(TableWidget<? extends DBTable> tableWidget) {
        this.tableWidget = tableWidget;
    }

    /**
     * @return the childFactory
     */
    public TableMemberChildFactory getChildFactory() {
        return childFactory;
    }

    /**
     * @param childFactory the childFactory to set
     */
    public void setChildFactory(TableMemberChildFactory childFactory) {
        this.childFactory = childFactory;
    }
}
